default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: your_app_development
  username: your_database_user
  password: your_database_password
  host: localhost

test:
  <<: *default
  database: your_app_test
  username: your_database_user
  password: your_database_password
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>